import { HouseMember } from "./HouseMember";

export class Person {
    constructor(
        public Name: string,
        public EntryDate: Date,
        public ActiveOrInactive: boolean,
        public MaritalStatus: string,
        public Age: number,
        public BornDate: Date,
        public Read: boolean,
        public Write: boolean,
        public SocialSecurity: boolean,
        public SocialSecurityType: string,
        public Education: string,
        public Nationality: string,
        public PhoneNumber: string,
        public Address: string,
        public Email: string,
        public Need_Doctor: boolean,
        public Need_Ophthalmologist: boolean,
        public Need_Mammography: boolean,
        public Need_Dentist: boolean,
        public Need_Gynecologist: boolean,
        public Need_Psychologist: boolean,
        public AbuseVictim: boolean,
        public SuicideAttempt: boolean,
        public SuicideToughts: boolean,
        public DrugsProblem: boolean,
        public AlcoholProblems: boolean,
        public TakeMedication: boolean,
        public Medication: Array<string>,
        public EmploymentSituation: string,
        public WorkingHours: number,
        public UnemployedDate: string,
        public SupportInstitutions: Array<string>,
        public PersonsInTheHouse: number,
        public UnderagePeople: number,
        public DisabilitiePersons: number,
        public HouseIncome: number,
        public IncomeSource: string,
        public HouseHolding: string,
        public HouseCondition: string,
        public HouseMembers: Array<HouseMember>,
        public _id?: string
    ) {}
}